package com.muzi.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.muzi.bean.SQLUserBean;

import com.muzi.bean.SQLUserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sQLUserBeanDaoConfig;

    private final SQLUserBeanDao sQLUserBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sQLUserBeanDaoConfig = daoConfigMap.get(SQLUserBeanDao.class).clone();
        sQLUserBeanDaoConfig.initIdentityScope(type);

        sQLUserBeanDao = new SQLUserBeanDao(sQLUserBeanDaoConfig, this);

        registerDao(SQLUserBean.class, sQLUserBeanDao);
    }
    
    public void clear() {
        sQLUserBeanDaoConfig.getIdentityScope().clear();
    }

    public SQLUserBeanDao getSQLUserBeanDao() {
        return sQLUserBeanDao;
    }

}
