package com.muzi.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SQLUSER_BEAN".
 */
public class SQLUserBean {

    private String id;
    private String orderNo;
    private String roomID;
    private String chargeTypeID;
    private String chargeSum;
    private String useScore;

    public SQLUserBean() {
    }

    public SQLUserBean(String id) {
        this.id = id;
    }

    public SQLUserBean(String id, String orderNo, String roomID, String chargeTypeID, String chargeSum, String useScore) {
        this.id = id;
        this.orderNo = orderNo;
        this.roomID = roomID;
        this.chargeTypeID = chargeTypeID;
        this.chargeSum = chargeSum;
        this.useScore = useScore;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getRoomID() {
        return roomID;
    }

    public void setRoomID(String roomID) {
        this.roomID = roomID;
    }

    public String getChargeTypeID() {
        return chargeTypeID;
    }

    public void setChargeTypeID(String chargeTypeID) {
        this.chargeTypeID = chargeTypeID;
    }

    public String getChargeSum() {
        return chargeSum;
    }

    public void setChargeSum(String chargeSum) {
        this.chargeSum = chargeSum;
    }

    public String getUseScore() {
        return useScore;
    }

    public void setUseScore(String useScore) {
        this.useScore = useScore;
    }

}
